### ISSUE TITLE
confused with the inputs

### ISSUE THREAD

**Issue by chenqihuang** [m-hasan-n/pooling#3]
First, this a wonderful research. 
I have a question about input of the network. In the code,  the Input only includes the position, but not the radial velocity, is it right? Thank you for your valuable time.

**Comment by m-hasan-n** [comment]
Thanks for your interest in our work. The number of inputs depends on the selected pooling strategy. If the pooling strategy is set to 'polar', then 3 inputs are used (radius, angle and radial velocity). For all other strategies, only 2 inputs (x, y) are used. You can set the the pooling strategy _args['pooling']_ and number of inputs _args['ip_dim']_ in 'model_args.py' script.
